Content-Aggregator/Models/Content.cs
namespace ContentAggregator.Models
{
    public class Content
    {
        public int ContentId { get; set; }
        public string Title { get; set; }
        public string OwnerId { get; set; }
        public string Url { get; set; }
        public string Description { get; set; }
        public ContentStatus Status { get; set; }
    }

    public enum ContentStatus
    {
        Submitted,
        Approved,
        Rejected
    }
}

Content-Aggregator/Controllers/CommentController.cs
using System.Threading.Tasks;
using ContentAggregator.Data.Repositories;
using ContentAggregator.Models;
using ContentAggregator.Models.CommentsViewModels;
using ContentAggregator.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ContentAggregator.Controllers
{
    [Authorize]
    public class CommentController : Controller
    {
        private readonly ICommentsRepository _commentsRepository;
        private readonly IContentRepository _contentRepository;
        private readonly IRequestUserProvider _requestUserProvider;

        public CommentController(ICommentsRepository commentsRepository,
            IContentRepository contentRepository,
            IRequestUserProvider requestUserProvider)
        {
            _commentsRepository = commentsRepository;
            _contentRepository = contentRepository;
            _requestUserProvider = requestUserProvider;
        }

        public async Task<IActionResult> Add(int contentId)
        {           
            var content = await _contentRepository.GetWithId(contentId);
            var vm = new CommentsViewModel {Comment = new Comments(), Content = content};
            return View(vm);
        }

        public async Task<IActionResult> Remove(int commentId)
        {
            var comment = await _commentsRepository.GetWithId(commentId);

            comment.IsRemoved = true;

            _commentsRepository.Update(comment);
            await _commentsRepository.SaveChangesAsync();

            return RedirectToAction("Details", "Content", new { id = comment.ContentId });
        }

        public async Task<IActionResult> BringBack(int commentId)
        {
            var comment = await _commentsRepository.GetWithId(commentId);
            comment.IsRemoved = false;

            _commentsRepository.Update(comment);
            await _commentsRepository.SaveChangesAsync();

            return RedirectToAction("Details", "Content", new { id = comment.ContentId });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add([Bind("CommentsId,ContentId,IsRemoved,Text,UserId")] Comments comment, int contentId)
        {
            if (!ModelState.IsValid) return View();

            var userId = _requestUserProvider.GetUserId();

            comment.ContentId = contentId;
            comment.UserId = userId;
            comment.IsRemoved = false;

            _commentsRepository.Add(comment);
            await _commentsRepository.SaveChangesAsync();

            return RedirectToAction("Details", "Content", new {id = contentId});
        }
    }
}

Content-Aggregator/Controllers/ContentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ContentAggregator.Data;
using ContentAggregator.Data.Repositories;
using ContentAggregator.Models;
using ContentAggregator.Models.ContentViewModels;
using ContentAggregator.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace Content_Aggregator.Controllers
{
    public class ContentController : Controller
    {
        private readonly IContentRepository _contentRepository;
        private readonly ICommentsRepository _commentsRepository;
        private readonly IRequestUserProvider _requestUserProvider;

        public ContentController(IContentRepository contentRepository,
            ICommentsRepository commentsRepository,
            IRequestUserProvider requestUserProvider)
        {
            _contentRepository = contentRepository;
            _commentsRepository = commentsRepository;
            _requestUserProvider = requestUserProvider;
        }

        // GET: Content
        public async Task<IActionResult> Index()
        {
            return View(await _contentRepository.GetApproved());
        }

        // GET: Content/WaitingRoom
        public async Task<IActionResult> WaitingRoom()
        {
            return View(await _contentRepository.GetSubmitted());
        }

        // GET: Content/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var content = await _contentRepository.GetWithId(id.Value);
            if (content == null)
            {
                return NotFound();
            }

            var comments = await _commentsRepository.GetWithContentId(content.ContentId);
            var vm = new ContentCommentsViewModel
            {
                Content = content,
                Comments = comments
            };

            return View(vm);
        }

        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Approve(int contentId)
        {
            var content = await _contentRepository.GetWithId(contentId);
            if (content == null)
            {
                return NotFound();
            }

            content.Status = ContentStatus.Approved;

            _contentRepository.Update(content);
            await _contentRepository.SaveChangesAsync();

            return RedirectToAction("WaitingRoom", "Content");
        }

        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Reject(int contentId)
        {
            var content = await _contentRepository.GetWithId(contentId);
            if (content == null)
            {
                return NotFound();
            }

            content.Status = ContentStatus.Rejected;

            _contentRepository.Update(content);
            await _contentRepository.SaveChangesAsync();

            return RedirectToAction("WaitingRoom", "Content");
        }

        // GET: Content/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }
        // POST: Content/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ContentId,Title,OwnerId,Url,Description,Status")] Content content)
        {
            if (!ModelState.IsValid) return View();

            var ownerId = _requestUserProvider.GetUserId();

            content.OwnerId = ownerId;
            content.Status = ContentStatus.Submitted;

            _contentRepository.Add(content);
            await _contentRepository.SaveChangesAsync();

            return RedirectToAction("Details", "Content", new {id = content.ContentId});
        }

        // GET: Content/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var content = await _contentRepository.GetWithId(id.Value);
            if (content == null)
            {
                return NotFound();
            }
            return View(content);
        }

        // POST: Content/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ContentId,Title,OwnerId,Url,Description,Status")] Content content)
        {
            if (id != content.ContentId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _contentRepository.Update(content);
                    await _contentRepository.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ContentExists(content.ContentId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(content);
        }

        // GET: Content/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var content = await _contentRepository.GetWithId(id.Value);
            if (content == null)
            {
                return NotFound();
            }

            return View(content);
        }

        // POST: Content/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var content = await _contentRepository.GetWithId(id);

            _contentRepository.Remove(content);
            await _contentRepository.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ContentExists(int id)
        {
            return _contentRepository.Exists(id);
        }
    }
}

Content-Aggregator/Views/Content/Create.cshtml
@model ContentAggregator.Models.Content

@{
    ViewData["Title"] = "Create";
}

<h2>Add new</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Url" class="control-label"></label>
                <input asp-for="Url" class="form-control" />
                <span asp-validation-for="Url" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Content-Aggregator/Views/Content/Delete.cshtml
@model ContentAggregator.Models.Content

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Content</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OwnerId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OwnerId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Url)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Url)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ContentId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Content-Aggregator/Views/Content/Details.cshtml
@model ContentAggregator.Models.ContentViewModels.ContentCommentsViewModel

@{
    ViewData["Title"] = @Model.Content.Title;
}

<h2><a href="@Model.Content.Url">@Model.Content.Title</a></h2>
<span>@Model.Content.Description</span>

<div>
    <a asp-authorize asp-roles="Administrator" asp-action="Edit" asp-route-id="@Model.Content.ContentId">Edit</a> |
    <a asp-action="Index">Back to browsing</a>
</div>

<h4>Comments</h4>
<div><a asp-controller="Comment" asp-action="Add" asp-route-contentId="@Model.Content.ContentId">Add comment</a></div>

@foreach (var item in Model.Comments)
{
    if (item.IsRemoved)
    {
<div asp-authorize asp-roles="Administrator" style="margin-bottom: 25px">
    <div><strong>@item.UserId</strong></div>
    <div><i style="color: red">Removed comment</i></div>
    <div>@item.Text</div>
    <div asp-authorize asp-roles="Administrator"><a asp-controller="Comment" asp-action="BringBack" asp-route-commentId="@item.CommentsId">Bring back</a></div>
</div>
    }
     else
     {
         <div style="margin-bottom: 25px">
             <div><strong>@item.UserId</strong></div>
             <div>@item.Text</div>
             <div asp-authorize asp-roles="Administrator"><a asp-controller="Comment" asp-action="Remove" asp-route-commentId="@item.CommentsId">Remove</a></div>
         </div>
     }
}

Content-Aggregator/Views/Content/Edit.cshtml
@model ContentAggregator.Models.Content

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Content</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ContentId" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OwnerId" class="control-label"></label>
                <input asp-for="OwnerId" class="form-control" />
                <span asp-validation-for="OwnerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Url" class="control-label"></label>
                <input asp-for="Url" class="form-control" />
                <span asp-validation-for="Url" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status" asp-items="@Html.GetEnumSelectList(typeof(ContentStatus))"class="form-control"></select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Content-Aggregator/Views/Content/Index.cshtml
@model IEnumerable<ContentAggregator.Models.Content>

@{
    ViewData["Title"] = "Browse";
}

<p>
    <a asp-action="Create">Add new!</a>
</p>

@foreach (var item in Model)
{
    <div>
        <h3><a asp-action="Details" asp-route-id="@item.ContentId">@item.Title</a></h3>
        <a href="@item.Url">(Direct URL)</a><br/>
        <span>@item.Description</span><br/>
        <span><strong>Rating:</strong> 12345</span><br/>
        <span><a>12345 comments</a></span><br/>
    </div>
}

Content-Aggregator/Views/Content/WaitingRoom.cshtml
@model IEnumerable<ContentAggregator.Models.Content>

@{
    ViewData["Title"] = "Browse";
}

<p>
    <a asp-action="Create">Add new!</a>
</p>

@foreach (var item in Model)
{
    <div>
        <h3><a asp-action="Details" asp-route-id="@item.ContentId">@item.Title</a></h3>
        <a href="@item.Url">(Direct URL)</a><br/>
        <span>@item.Description</span><br/>
        <div asp-authorize asp-roles="Administrator">
            <a asp-action="Approve" asp-route-contentId="@item.ContentId">Accept</a> | 
            <a asp-action="Reject" asp-route-contentId="@item.ContentId">Reject</a>
        </div>
    </div>
}